---
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.2
script: bundle exec rake spec
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.6.0"
matrix:
  exclude:
    - rvm: 2.1.2
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.1.2
      env: PUPPET_VERSION="~> 3.1.0"
    - rvm: 2.1.2
      env: PUPPET_VERSION="~> 3.2.0"
    - rvm: 2.1.2
      env: PUPPET_VERSION="~> 3.3.0"
    - rvm: 2.1.2
      env: PUPPET_VERSION="~> 3.4.0"
notifications:
  email:
    - javier@netmanagers.com.ar
